# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - configmap.yaml


images:
  - name: product-service
    newName: <account-id>.dkr.ecr.us-east-1.amazonaws.com/product-service
    newTag: latest
  - name: cart-service
    newName: <account-id>.dkr.ecr.us-east-1.amazonaws.com/cart-service
    newTag: latest
  - name: order-service
    newName: <account-id>.dkr.ecr.us-east-1.amazonaws.com/order-service
    newTag: latest
  - name: payment-service
    newName: <account-id>.dkr.ecr.us-east-1.amazonaws.com/payment-service
    newTag: latest
  - name: user-service
    newName: <account-id>.dkr.ecr.us-east-1.amazonaws.com/user-service
    newTag: latest
  - name: inventory-service
    newName: <account-id>.dkr.ecr.us-east-1.amazonaws.com/inventory-service
    newTag: latest
  - name: shipping-service
    newName: <account-id>.dkr.ecr.us-east-1.amazonaws.com/shipping-service
    newTag: latest
  - name: notification-service
    newName: <account-id>.dkr.ecr.us-east-1.amazonaws.com/notification-service
    newTag: latest